name: simple_blog
description: "Mobile Developer Technical Assessment: Simple Blog App with GraphQL Integration"


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  auto_route: ^8.0.3
  bloc: ^8.1.4
  bloc_test: ^9.1.7
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  fancy_shimmer_image: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_markdown: ^0.7.1
  flutter_svg: ^2.0.0
  font_awesome_flutter: ^10.7.0
  freezed_annotation: ^2.4.1
  get_it: ^7.7.0
  get_it_mixin: ^4.2.2
  github_signin_promax: ^0.0.7+2
  google_fonts: ^4.0.4
  injectable: ^2.4.1
  json_annotation: ^4.8.1
  markdown_viewer: ^0.6.2
  shared_preferences: ^2.2.3
  toastification: ^1.2.1

dev_dependencies:
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.9
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  injectable_generator: ^2.6.1
  json_serializable: ^6.7.1
  mocktail: ^1.0.3

# run: flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
